MODULE_NAME=lz4e
MODULE_OBJ=build/$MODULE_NAME.ko
MODULE_PARAMETERS=/sys/module/$MODULE_NAME/parameters

DEVICE_MAPPER=$MODULE_PARAMETERS/mapper
DEVICE_UNMAPPER=$MODULE_PARAMETERS/unmapper
REQUEST_STATS=$MODULE_PARAMETERS/stats

UNDERLYING_DEVICE=/dev/ram0
TEST_DEVICE=/dev/lz4e0
DISK_SIZE_IN_KB=307200

TEST_FILES_DIR=test/test_files
TEMP_DIR=test/tmp

PROXY_TEST_FILE1=$TEST_FILES_DIR/01.txt
PROXY_TEST_FILE2=$TEST_FILES_DIR/02.txt
PROXY_TEST_FILE3=$TEST_FILES_DIR/03.jpg

PROXY_TEST_FILE_LEN1=$(stat --print="%s" $PROXY_TEST_FILE1)
PROXY_TEST_FILE_LEN2=$(stat --print="%s" $PROXY_TEST_FILE2)
PROXY_TEST_FILE_LEN3=$(stat --print="%s" $PROXY_TEST_FILE3)

PROXY_OUTPUT_FILE1=$TEMP_DIR/01.txt
PROXY_OUTPUT_FILE2=$TEMP_DIR/02.txt
PROXY_OUTPUT_FILE3=$TEMP_DIR/03.jpg

DEVICE_ZERO=/dev/zero
DEVICE_RANDOM=/dev/random
