MODULE_NAME=blk_comp
MODULE_OBJ=build/$MODULE_NAME.ko
MODULE_PARAMETERS=/sys/module/$MODULE_NAME/parameters

DEVICE_MAPPER=$MODULE_PARAMETERS/mapper
DEVICE_UNMAPPER=$MODULE_PARAMETERS/unmapper

UNDERLYING_DEVICE=/dev/ram0
TEST_DEVICE=/dev/blk-comp-0
DISK_SIZE_IN_KB=307200

TEST_FILES_DIR=test/test_files
TEMP_DIR=test/tmp

PROXY_TEST_FILE=$TEST_FILES_DIR/01.txt
PROXY_TEST_FILE_LEN=$(stat --print="%s" $PROXY_TEST_FILE)
PROXY_OUTPUT_FILE=$TEMP_DIR/01.txt
